[package]
name = "actyxos_sdk"
version = "0.5.0"
authors = ["Actyx AG <developer@actyx.io>"]
edition = "2018"
description = "Tools for interacting with the services of an ActyxOS node"
readme = "README.md"
documentation = "https://docs.rs/actyxos_sdk"
homepage = "https://developer.actyx.com"
license = "Apache-2.0"
keywords = ["distributed", "decentralized", "event-sourcing"]
categories = ["network-programming"]

[package.metadata.docs.rs]
features = ["client", "dataflow"]

[features]
client = ["reqwest", "url", "futures", "bytes"]
dataflow = ["abomonation", "abomonation_derive"]
sqlite = ["rusqlite"]
postgresql = ["postgres-types", "bytes"]

[dependencies]
abomonation = { version = "~0.7", optional = true }
abomonation_derive = { version = "~0.5", optional = true }
actyxos_sdk_macros = { version = "~0.2" }
anyhow = "1"
base64 = "0.12"
bytes = { version = "~0.5", optional = true }
chrono = { version = "~0.4" }
derive_more = "~0.99"
fixed = { version = "~0.5", features = [] }
futures = { version = "~0.3", optional = true }
intern-arc = { version = "0.1" }
multibase = "0.8"
num-traits = "0.2"
postgres-types = { version = "0.1", optional = true }
reqwest = { version = "~0.10", features = ["json", "gzip", "stream", "native-tls-vendored"], optional = true }
rusqlite = { version = "0.24", optional = true, features = ["bundled"] }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_cbor = "~0.11"
serde_json = "1.0"
serde-transcode = "1.0"
tracing = "0.1.16"
typenum = "~1.12"
url = { version = "~2.1", optional = true }

[dev-dependencies]
quickcheck = "0.9"
rand = "0.7"
tokio = { version = "~0.2", features = ["rt-threaded", "macros"] }

[[example]]
name = "offsets"
path = "examples/offsets.rs"
required-features = ["client"]
