[package]
name = "actyxos_sdk"
version = "0.4.0"
authors = ["Actyx AG <developer@actyx.io>"]
edition = "2018"
description = "Tools for interacting with the services of an ActyxOS node"
readme = "README.md"
documentation = "https://docs.rs/actyxos_sdk"
homepage = "https://developer.actyx.com"
license = "Apache-2.0"
keywords = ["distributed", "decentralized", "event-sourcing"]
categories = ["network-programming"]

[package.metadata.docs.rs]
features = ["client", "dataflow"]

[features]
client = ["reqwest", "url", "futures", "bytes"]
dataflow = ["abomonation", "abomonation_derive"]
sqlite = ["rusqlite"]
postgresql = ["postgres-types", "bytes"]

[dependencies]
abomonation = { version = "~0.7", optional = true }
abomonation_derive = { version = "~0.5", optional = true }
actyxos_sdk_macros = { version = "~0.2" }
anyhow = "1"
intern-arc = { version = "0.1" }
bytes = { version = "~0.5", optional = true }
chrono = { version = "~0.4" }
derive_more = "~0.99"
futures = { version = "~0.3", optional = true }
multibase = "0.8"
num-traits = "0.2"
postgres-types = { version = "0.1", optional = true }
reqwest = { version = "~0.10", features = ["json", "gzip", "stream"], optional = true }
rusqlite = { version = "0.20", optional = true }
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde-transcode = "1.0"
serde_cbor = "~0.11"
url = { version = "~2.1", optional = true }
fixed = { version = "~0.5", features = [] }
typenum = "~1.12"

[dev-dependencies]
quickcheck = "0.9"
rand = "0.7"
tokio = { version = "~0.2", features = ["rt-threaded", "macros"] }

[[example]]
name = "offsets"
path = "examples/offsets.rs"
required-features = ["client"]
