[package]
name = "actyxos_sdk"
version = "0.5.0"
authors = ["Actyx AG <developer@actyx.io>"]
edition = "2018"
description = "Tools for interacting with the services of an ActyxOS node"
readme = "README.md"
documentation = "https://docs.rs/actyxos_sdk"
homepage = "https://developer.actyx.com"
license = "Apache-2.0"
keywords = ["distributed", "decentralized", "event-sourcing"]
categories = ["network-programming"]

[package.metadata.docs.rs]
features = ["client", "dataflow"]

[features]
client = ["reqwest", "url", "futures", "bytes"]
dataflow = ["abomonation", "abomonation_derive"]
sqlite = ["rusqlite"]
postgresql = ["postgres-types", "bytes"]
arb = ["quickcheck", "rand"]

[dependencies]
abomonation = { version = "0.7.3", optional = true }
abomonation_derive = { version = "0.5.0", optional = true }
actyxos_sdk_macros = { version = "~0.2", path = "../sdk_macros" }
anyhow = "1.0.38"
base64 = "0.13.0"
bytes = { version = "1.0.1", optional = true }
chrono = "0.4.19"
derive_more = "0.99.11"
fixed = { version = "0.5.0", features = [] }
futures = { version = "0.3.12", optional = true }
intern-arc = "0.1.0"
libipld = { version = "0.11.0", default-features = false, features = ["dag-cbor", "derive"] }
multibase = "0.9.1"
num-traits = "0.2.14"
postgres-types = { version = "0.2.0", optional = true }
reqwest = { version = "0.11.0", features = ["json", "gzip", "stream", "native-tls-vendored"], optional = true }
rusqlite = { version = "0.24.2", optional = true, features = ["bundled"] }
serde = { version = "1.0.120", features = ["derive", "rc"] }
serde_cbor = "0.11.1"
serde_json = "1.0.61"
serde-transcode = "1.1.0"
tracing = "0.1.22"
typenum = "1.12.0"
url = { version = "2.2.0", optional = true }
quickcheck = { version = "1.0.3", optional = true }
rand = { version = "0.8.2", optional = true }

[dev-dependencies]
quickcheck = "1.0.3"
rand = "0.8.2"
tokio = { version = "1.0.2", features = ["rt-multi-thread", "macros"] }

[[example]]
name = "offsets"
path = "examples/offsets.rs"
required-features = ["client"]
