[package]
name = "actyx_sdk"
version = "0.2.0"
authors = ["Actyx AG <developer@actyx.io>"]
edition = "2018"
description = "Tools for interacting with the services of an Actyx node"
readme = "README.md"
documentation = "https://docs.rs/actyx_sdk"
homepage = "https://developer.actyx.com/docs/reference/rust-sdk/"
license = "Apache-2.0"
keywords = ["distributed", "decentralized", "event-sourcing"]
categories = ["network-programming"]

[package.metadata.docs.rs]
features = ["client", "dataflow"]

[features]
client = ["reqwest", "url", "bytes"]
dataflow = ["abomonation", "abomonation_derive"]
sqlite = ["rusqlite"]
postgresql = ["postgres-types", "bytes"]
arb = ["quickcheck", "rand"]
with-tokio = ["tokio"]

[dependencies]
abomonation = { version = "0.7.3", optional = true }
abomonation_derive = { version = "0.5.0", optional = true }
actyx_sdk_macros = { version = "0.1", path = "../sdk_macros" }
anyhow = "1.0.42"
async-trait = "0.1.51"
base64 = "0.13.0"
bytes = { version = "1.0.1", optional = true }
chrono = "0.4.19"
derive_more = "0.99.16"
fixed = { version = "1.9.0", features = [] }
futures = "0.3.16"
intern-arc = "0.1.0"
libipld = { version = "0.12.0", default-features = false, features = ["dag-cbor", "derive"] }
maplit = "1.0.2"
multibase = "0.9.1"
num-traits = "0.2.14"
once_cell = "1.8.0"
pest = "2.1.3"
pest_derive = "2.1.0"
postgres-types = { version = "0.2.1", optional = true }
quickcheck = { version = "1.0.3", optional = true }
rand = { version = "0.8.4", optional = true }
reduce = "0.1.4"
reqwest = { version = "0.11.4", features = ["json", "gzip", "stream", "native-tls-vendored"], optional = true }
rusqlite = { version = "0.25.3", optional = true, features = ["bundled"] }
serde = { version = "1.0.127", features = ["derive", "rc"] }
serde_cbor = "0.11.1"
serde_json = "1.0.66"
serde-transcode = "1.1.1"
tokio = { version = "1.9.0", features = ["time"], optional = true }
tracing = "0.1.26"
typenum = "1.13.0"
unicode-normalization = "0.1.19"
url = { version = "2.2.2", optional = true }

[dev-dependencies]
futures-timer = "3.0.2"
hex = "0.4.3"
quickcheck = "1.0.3"
quickcheck_derive = "0.3.0"
rand = "0.8.4"
tokio = { version = "1.9.0", features = ["rt-multi-thread", "macros"] }

[[example]]
name = "query"
path = "examples/query.rs"
required-features = ["client"]

[[example]]
name = "publish"
path = "examples/publish.rs"
required-features = ["client"]
