[package]
name = "libp2p-broadcast"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
fnv = "1.0.7"
futures = "0.3.12"
libp2p = { version = "0.35.0", default-features = false }
