[package]
name = "runtime"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
actyx_sdk = { path = "../../sdk" }
anyhow = "1.0.42"
cbor-data = "0.5.0"
derive_more = "0.99.16"
itertools = "0.10.1"
tracing = "0.1.26"

[dev-dependencies]
criterion = "0.3.5"
quickcheck = "1.0.3"
spectral = "0.6.0"

[[bench]]
name = "bench_runtime_query"
harness = false
