[package]
name = "runtime"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
actyx_sdk = { path = "../../sdk" }
anyhow = "1.0.52"
cbor-data = "0.5.0"
derive_more = "0.99.17"
itertools = "0.10.3"
tracing = "0.1.29"

[dev-dependencies]
quickcheck = "1.0.3"
spectral = "0.6.0"
