[package]
name = "runtime"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
actyx_sdk = { path = "../../sdk" }
ax-futures-util = { path = "../ax-futures-util" }
anyhow = "1.0.52"
cbor-data = { version = "0.8.3", features = ["rfc3339"] }
derive_more = "0.99.17"
futures = "0.3.16"
itertools = "0.10.3"
tracing = "0.1.29"
swarm = { path = "../swarm" }
parking_lot = "0.11.1"
chrono = "0.4.19"
num-bigint = "0.4.3"

[dev-dependencies]
criterion = "0.3.5"
maplit = "1.0.2"
quickcheck = "1.0.3"
spectral = "0.6.0"
tokio = { version = "1.9.0", features = ["full"] }

[[bench]]
name = "bench_runtime_query"
harness = false
