[package]
name = "runtime"
version = "0.1.0"
authors = ["Roland Kuhn <rk@rkuhn.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actyxos_sdk = { version = "0.5.0", path = "../../sdk" }
trees = { version = "0.1", path = "../trees" }
