//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Actyx.Documents.Driver {

public enum AMstatus {
  A_MSTATUS_OK,
  A_MSTATUS_ERROR,
  A_MSTATUS_INVALID_RESULT
}

}
