//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Actyx.Documents.Driver {

public enum AMvalue_Tag {
  A_MVALUE_ACTOR_ID,
  A_MVALUE_BOOLEAN,
  A_MVALUE_BYTES,
  A_MVALUE_CHANGE_HASHES,
  A_MVALUE_CHANGES,
  A_MVALUE_COUNTER,
  A_MVALUE_DOC,
  A_MVALUE_F64,
  A_MVALUE_INT,
  A_MVALUE_NULL,
  A_MVALUE_OBJ_ID,
  A_MVALUE_STR,
  A_MVALUE_STRINGS,
  A_MVALUE_TIMESTAMP,
  A_MVALUE_UINT,
  A_MVALUE_SYNC_MESSAGE,
  A_MVALUE_SYNC_STATE,
  A_MVALUE_VOID
}

}
