//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Actyx.Documents.Driver {

class automergePINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="SWIGRegisterExceptionCallbacks_automerge")]
    public static extern void SWIGRegisterExceptionCallbacks_automerge(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_automerge")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_automerge(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_automerge(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_automerge(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="SWIGRegisterStringCallback_automerge")]
    public static extern void SWIGRegisterStringCallback_automerge(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_automerge(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static automergePINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_new_bytes___")]
  public static extern global::System.IntPtr new_bytes(int jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_delete_bytes___")]
  public static extern void delete_bytes(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_bytes_getitem___")]
  public static extern byte bytes_getitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_bytes_setitem___")]
  public static extern void bytes_setitem(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2, byte jarg3);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMbyteSpan_src_set___")]
  public static extern void AMbyteSpan_src_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMbyteSpan_src_get___")]
  public static extern global::System.IntPtr AMbyteSpan_src_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMbyteSpan_count_set___")]
  public static extern void AMbyteSpan_count_set(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMbyteSpan_count_get___")]
  public static extern uint AMbyteSpan_count_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_new_AMbyteSpan___")]
  public static extern global::System.IntPtr new_AMbyteSpan();

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_delete_AMbyteSpan___")]
  public static extern void delete_AMbyteSpan(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeHashes_detail_set___")]
  public static extern void AMchangeHashes_detail_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeHashes_detail_get___")]
  public static extern global::System.IntPtr AMchangeHashes_detail_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_new_AMchangeHashes___")]
  public static extern global::System.IntPtr new_AMchangeHashes();

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_delete_AMchangeHashes___")]
  public static extern void delete_AMchangeHashes(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchanges_detail_set___")]
  public static extern void AMchanges_detail_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchanges_detail_get___")]
  public static extern global::System.IntPtr AMchanges_detail_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_new_AMchanges___")]
  public static extern global::System.IntPtr new_AMchanges();

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_delete_AMchanges___")]
  public static extern void delete_AMchanges(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMstrings_detail_set___")]
  public static extern void AMstrings_detail_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMstrings_detail_get___")]
  public static extern global::System.IntPtr AMstrings_detail_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_new_AMstrings___")]
  public static extern global::System.IntPtr new_AMstrings();

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_delete_AMstrings___")]
  public static extern void delete_AMstrings(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_tag_set___")]
  public static extern void AMvalue_tag_set(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_tag_get___")]
  public static extern int AMvalue_tag_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_actor_id_set___")]
  public static extern void AMvalue_actor_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_actor_id_get___")]
  public static extern global::System.IntPtr AMvalue_actor_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_boolean_set___")]
  public static extern void AMvalue_boolean_set(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_boolean_get___")]
  public static extern bool AMvalue_boolean_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_bytes_set___")]
  public static extern void AMvalue_bytes_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_bytes_get___")]
  public static extern global::System.IntPtr AMvalue_bytes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_change_hashes_set___")]
  public static extern void AMvalue_change_hashes_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_change_hashes_get___")]
  public static extern global::System.IntPtr AMvalue_change_hashes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_changes_set___")]
  public static extern void AMvalue_changes_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_changes_get___")]
  public static extern global::System.IntPtr AMvalue_changes_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_counter_set___")]
  public static extern void AMvalue_counter_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_counter_get___")]
  public static extern long AMvalue_counter_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_doc_set___")]
  public static extern void AMvalue_doc_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_doc_get___")]
  public static extern global::System.IntPtr AMvalue_doc_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_f64_set___")]
  public static extern void AMvalue_f64_set(global::System.Runtime.InteropServices.HandleRef jarg1, double jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_f64_get___")]
  public static extern double AMvalue_f64_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_int__set___")]
  public static extern void AMvalue_int__set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_int__get___")]
  public static extern long AMvalue_int__get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_obj_id_set___")]
  public static extern void AMvalue_obj_id_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_obj_id_get___")]
  public static extern global::System.IntPtr AMvalue_obj_id_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_str_set___")]
  public static extern void AMvalue_str_set(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_str_get___")]
  public static extern string AMvalue_str_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_strings_set___")]
  public static extern void AMvalue_strings_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_strings_get___")]
  public static extern global::System.IntPtr AMvalue_strings_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_timestamp_set___")]
  public static extern void AMvalue_timestamp_set(global::System.Runtime.InteropServices.HandleRef jarg1, long jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_timestamp_get___")]
  public static extern long AMvalue_timestamp_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_uint__set___")]
  public static extern void AMvalue_uint__set(global::System.Runtime.InteropServices.HandleRef jarg1, ulong jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_uint__get___")]
  public static extern ulong AMvalue_uint__get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_sync_message_set___")]
  public static extern void AMvalue_sync_message_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_sync_message_get___")]
  public static extern global::System.IntPtr AMvalue_sync_message_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_sync_state_set___")]
  public static extern void AMvalue_sync_state_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMvalue_sync_state_get___")]
  public static extern global::System.IntPtr AMvalue_sync_state_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_new_AMvalue___")]
  public static extern global::System.IntPtr new_AMvalue();

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_delete_AMvalue___")]
  public static extern void delete_AMvalue(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncHaves_detail_set___")]
  public static extern void AMsyncHaves_detail_set(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncHaves_detail_get___")]
  public static extern global::System.IntPtr AMsyncHaves_detail_get(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_new_AMsyncHaves___")]
  public static extern global::System.IntPtr new_AMsyncHaves();

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_delete_AMsyncHaves___")]
  public static extern void delete_AMsyncHaves(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMactorIdBytes___")]
  public static extern global::System.IntPtr AMactorIdBytes(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMactorIdInit___")]
  public static extern global::System.IntPtr AMactorIdInit();

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMactorIdInitBytes___")]
  public static extern global::System.IntPtr AMactorIdInitBytes(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMactorIdInitStr___")]
  public static extern global::System.IntPtr AMactorIdInitStr(string jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMactorIdStr___")]
  public static extern string AMactorIdStr(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeActorId___")]
  public static extern global::System.IntPtr AMchangeActorId(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeCompress___")]
  public static extern void AMchangeCompress(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeDeps___")]
  public static extern global::System.IntPtr AMchangeDeps(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeExtraBytes___")]
  public static extern global::System.IntPtr AMchangeExtraBytes(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeFromBytes___")]
  public static extern global::System.IntPtr AMchangeFromBytes(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeHash___")]
  public static extern global::System.IntPtr AMchangeHash(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeIsEmpty___")]
  public static extern bool AMchangeIsEmpty(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeMaxOp___")]
  public static extern ulong AMchangeMaxOp(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeMessage___")]
  public static extern string AMchangeMessage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeSeq___")]
  public static extern ulong AMchangeSeq(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeSize___")]
  public static extern uint AMchangeSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeStartOp___")]
  public static extern ulong AMchangeStartOp(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeTime___")]
  public static extern long AMchangeTime(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeRawBytes___")]
  public static extern global::System.IntPtr AMchangeRawBytes(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeLoadDocument___")]
  public static extern global::System.IntPtr AMchangeLoadDocument(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeHashesAdvance___")]
  public static extern void AMchangeHashesAdvance(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeHashesCmp___")]
  public static extern int AMchangeHashesCmp(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeHashesInit___")]
  public static extern global::System.IntPtr AMchangeHashesInit(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeHashesNext___")]
  public static extern global::System.IntPtr AMchangeHashesNext(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeHashesPrev___")]
  public static extern global::System.IntPtr AMchangeHashesPrev(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeHashesSize___")]
  public static extern uint AMchangeHashesSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangeHashesReversed___")]
  public static extern global::System.IntPtr AMchangeHashesReversed(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangesAdvance___")]
  public static extern void AMchangesAdvance(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangesEqual___")]
  public static extern bool AMchangesEqual(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangesNext___")]
  public static extern global::System.IntPtr AMchangesNext(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangesPrev___")]
  public static extern global::System.IntPtr AMchangesPrev(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangesSize___")]
  public static extern uint AMchangesSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMchangesReversed___")]
  public static extern global::System.IntPtr AMchangesReversed(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMapplyChanges___")]
  public static extern global::System.IntPtr AMapplyChanges(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMcreate___")]
  public static extern global::System.IntPtr AMcreate();

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMcommit___")]
  public static extern global::System.IntPtr AMcommit(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMdup___")]
  public static extern global::System.IntPtr AMdup(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMequal___")]
  public static extern bool AMequal(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMgenerateSyncMessage___")]
  public static extern global::System.IntPtr AMgenerateSyncMessage(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMgetActor___")]
  public static extern global::System.IntPtr AMgetActor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMgetChanges___")]
  public static extern global::System.IntPtr AMgetChanges(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMgetChangesAdded___")]
  public static extern global::System.IntPtr AMgetChangesAdded(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMgetHeads___")]
  public static extern global::System.IntPtr AMgetHeads(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMgetMissingDeps___")]
  public static extern global::System.IntPtr AMgetMissingDeps(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMgetLastLocalChange___")]
  public static extern global::System.IntPtr AMgetLastLocalChange(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMkeys___")]
  public static extern global::System.IntPtr AMkeys(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMload___")]
  public static extern global::System.IntPtr AMload(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMloadIncremental___")]
  public static extern global::System.IntPtr AMloadIncremental(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMmerge___")]
  public static extern global::System.IntPtr AMmerge(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMobjSize___")]
  public static extern uint AMobjSize(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMpendingOps___")]
  public static extern uint AMpendingOps(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMreceiveSyncMessage___")]
  public static extern global::System.IntPtr AMreceiveSyncMessage(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMrollback___")]
  public static extern uint AMrollback(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsave___")]
  public static extern global::System.IntPtr AMsave(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsaveIncremental___")]
  public static extern global::System.IntPtr AMsaveIncremental(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsetActor___")]
  public static extern global::System.IntPtr AMsetActor(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMspliceText___")]
  public static extern global::System.IntPtr AMspliceText(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, uint jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMtext___")]
  public static extern global::System.IntPtr AMtext(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, global::System.Runtime.InteropServices.HandleRef jarg3);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMlistDelete___")]
  public static extern global::System.IntPtr AMlistDelete(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMlistGet___")]
  public static extern global::System.IntPtr AMlistGet(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMlistIncrement___")]
  public static extern global::System.IntPtr AMlistIncrement(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, long jarg4);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMlistPutBool___")]
  public static extern global::System.IntPtr AMlistPutBool(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, bool jarg4, bool jarg5);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMlistPutBytes___")]
  public static extern global::System.IntPtr AMlistPutBytes(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, bool jarg4, global::System.Runtime.InteropServices.HandleRef jarg5, uint jarg6);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMlistPutCounter___")]
  public static extern global::System.IntPtr AMlistPutCounter(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, bool jarg4, long jarg5);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMlistPutF64___")]
  public static extern global::System.IntPtr AMlistPutF64(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, bool jarg4, double jarg5);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMlistPutInt___")]
  public static extern global::System.IntPtr AMlistPutInt(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, bool jarg4, long jarg5);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMlistPutNull___")]
  public static extern global::System.IntPtr AMlistPutNull(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMlistPutObject___")]
  public static extern global::System.IntPtr AMlistPutObject(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, bool jarg4, int jarg5);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMlistPutStr___")]
  public static extern global::System.IntPtr AMlistPutStr(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, bool jarg4, string jarg5);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMlistPutTimestamp___")]
  public static extern global::System.IntPtr AMlistPutTimestamp(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, bool jarg4, long jarg5);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMlistPutUint___")]
  public static extern global::System.IntPtr AMlistPutUint(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, uint jarg3, bool jarg4, ulong jarg5);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMmapDelete___")]
  public static extern global::System.IntPtr AMmapDelete(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMmapGet___")]
  public static extern global::System.IntPtr AMmapGet(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMmapIncrement___")]
  public static extern global::System.IntPtr AMmapIncrement(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, long jarg4);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMmapPutBool___")]
  public static extern global::System.IntPtr AMmapPutBool(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMmapPutBytes___")]
  public static extern global::System.IntPtr AMmapPutBytes(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, global::System.Runtime.InteropServices.HandleRef jarg4, uint jarg5);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMmapPutCounter___")]
  public static extern global::System.IntPtr AMmapPutCounter(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, long jarg4);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMmapPutNull___")]
  public static extern global::System.IntPtr AMmapPutNull(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMmapPutObject___")]
  public static extern global::System.IntPtr AMmapPutObject(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMmapPutF64___")]
  public static extern global::System.IntPtr AMmapPutF64(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, double jarg4);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMmapPutInt___")]
  public static extern global::System.IntPtr AMmapPutInt(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, long jarg4);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMmapPutStr___")]
  public static extern global::System.IntPtr AMmapPutStr(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, string jarg4);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMmapPutTimestamp___")]
  public static extern global::System.IntPtr AMmapPutTimestamp(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, long jarg4);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMmapPutUint___")]
  public static extern global::System.IntPtr AMmapPutUint(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2, string jarg3, ulong jarg4);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMerrorMessage___")]
  public static extern string AMerrorMessage(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMfree___")]
  public static extern void AMfree(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMresultSize___")]
  public static extern uint AMresultSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMresultStatus___")]
  public static extern int AMresultStatus(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMresultValue___")]
  public static extern global::System.IntPtr AMresultValue(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMstringsAdvance___")]
  public static extern void AMstringsAdvance(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMstringsCmp___")]
  public static extern int AMstringsCmp(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMstringsNext___")]
  public static extern string AMstringsNext(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMstringsPrev___")]
  public static extern string AMstringsPrev(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMstringsSize___")]
  public static extern uint AMstringsSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMstringsReversed___")]
  public static extern global::System.IntPtr AMstringsReversed(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncHaveLastSync___")]
  public static extern global::System.IntPtr AMsyncHaveLastSync(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncHavesAdvance___")]
  public static extern void AMsyncHavesAdvance(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncHavesEqual___")]
  public static extern bool AMsyncHavesEqual(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncHavesNext___")]
  public static extern global::System.IntPtr AMsyncHavesNext(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncHavesPrev___")]
  public static extern global::System.IntPtr AMsyncHavesPrev(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncHavesSize___")]
  public static extern uint AMsyncHavesSize(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncHavesReversed___")]
  public static extern global::System.IntPtr AMsyncHavesReversed(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncMessageChanges___")]
  public static extern global::System.IntPtr AMsyncMessageChanges(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncMessageDecode___")]
  public static extern global::System.IntPtr AMsyncMessageDecode(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncMessageEncode___")]
  public static extern global::System.IntPtr AMsyncMessageEncode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncMessageHaves___")]
  public static extern global::System.IntPtr AMsyncMessageHaves(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncMessageHeads___")]
  public static extern global::System.IntPtr AMsyncMessageHeads(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncMessageNeeds___")]
  public static extern global::System.IntPtr AMsyncMessageNeeds(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncStateDecode___")]
  public static extern global::System.IntPtr AMsyncStateDecode(global::System.Runtime.InteropServices.HandleRef jarg1, uint jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncStateEncode___")]
  public static extern global::System.IntPtr AMsyncStateEncode(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncStateEqual___")]
  public static extern bool AMsyncStateEqual(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncStateInit___")]
  public static extern global::System.IntPtr AMsyncStateInit();

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncStateSharedHeads___")]
  public static extern global::System.IntPtr AMsyncStateSharedHeads(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncStateLastSentHeads___")]
  public static extern global::System.IntPtr AMsyncStateLastSentHeads(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncStateTheirHaves___")]
  public static extern global::System.IntPtr AMsyncStateTheirHaves(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncStateTheirHeads___")]
  public static extern global::System.IntPtr AMsyncStateTheirHeads(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_AMsyncStateTheirNeeds___")]
  public static extern global::System.IntPtr AMsyncStateTheirNeeds(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_ROOT_get___")]
  public static extern global::System.IntPtr ROOT_get();

  [global::System.Runtime.InteropServices.DllImport("automerge", EntryPoint="CSharp_ActyxfDocumentsfDriver_NOW_get___")]
  public static extern global::System.IntPtr NOW_get();
}

}
