[package]
name = "libp2p-streaming-response"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
derive_more = "0.99.11"
futures = "0.3.12"
libp2p = { version = "0.35.0", default-features = false }
serde = { version = "1.0.120", features = ["derive"] }
serde_cbor = "0.11.1"
thiserror = "1.0.23"
