[package]
name = "libp2p-streaming-response"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
derive_more = "0.99.16"
futures = { version = "0.3.15", package = "futures" }
libp2p = { version = "0.39.1", default-features = false }
serde = { version = "1.0.126", features = ["derive"] }
serde_cbor = "0.11.1"
thiserror = "1.0.26"
