---
ec2_chocolatey_version: 0.10.15
ec2_region: eu-central-1
ec2_instance_type: t2.small
ec2_image_id: ami-0da198ce94f235cdc
ec2_vpc_subnet_id: subnet-3a1d8350
ec2_user_data: user_data/winrm.txt
ec2_instance_role: ec2_iam_role
ec2_security_group: default
