---
- name: Deploy EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    ec2_key_name: "{{ lookup('env','EC2_KEY_NAME') }}"
    ec2_vpc_subnet_id: subnet-09149eb0bab11908d
    ec2_security_group: sg-0d942c552d4ff817c
    ec2_image_id: "{{ lookup('env','EC2_IMAGE_ID') }}"
    ec2_node_name: "{{ lookup('env','EC2_NODE_NAME') }}"
    ec2_instance_type: "{{ lookup('env','EC2_INSTANCE_TYPE') }}"
    ci_run: "{{ lookup('env','CI_RUN') }}"
    # fucking windows needs fucking exclamation mark otherwise it just won’t do anything
    # (Roland was **really** angry about that)
    ec2_administrator_password: A1!{{ lookup('env','EC2_ADMIN_PW') }}

  roles:
    - run_ec2

- name: Prepare Windows for Tests
  hosts: windows
  gather_facts: false
  vars:
    pw_package_file: ActyxOS-Installer.exe
    pw_package_path: "{{ lookup('env','LOCAL_INSTALLER_DIR') }}"
    pw_package_id: ActyxOS
    pw_package_args: "/S /background"
    pw_winssh_pubkey: "{{ lookup('env','SSH_PUBLIC_KEY') }}"
    ansible_connection: winrm
    ansible_ssh_port: 5986
    ansible_ssh_user: Administrator
    ansible_ssh_pass: A1!{{ lookup('env','EC2_ADMIN_PW') }}
    ansible_winrm_server_cert_validation: ignore

  roles:
    - prepare_windows

