[package]
name = "node-win"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[[bin]]
name = "actyx"
path = "src/main.rs"

[build-dependencies]
util = { path = "../util" }

[target."cfg(target_os = \"windows\")".dependencies]
anyhow = "1.0.40"
clap = "2.33.3"
crossbeam = "0.8.0"
structopt = "0.3.21"
systray2 = "0.5.0"
tracing = "0.1.25"
winapi = "0.3.9"
wintrap = "0.3.1"

[dependencies]
node = { path = "../node" }
util = { path = "../util"}
