export const API_V2_PATH = '/api/v2'
export const EVENTS_PATH = '/events'

export const AUTH_SEG = '/auth'
export const NODE_ID_SEG = '/node/id'
export const OFFSETS_SEG = '/offsets'
export const PUBLISH_SEG = '/publish'
export const QUERY_SEG = '/query'
export const SUBSCRIBE_SEG = '/subscribe'
export const SUBSCRIBE_MONOTONIC_SEG = '/subscribe_monotonic'
