module.exports = {
  howToSidebar: [
    {
      type: 'category',
      label: 'How-to Guides',
      collapsed: false,
      items: ['how-to-guides/overview'],
    },
    {
      type: 'category',
      label: 'Local Development',
      collapsed: true,
      items: [
        'how-to-guides/local-development/installing-actyx',
        'how-to-guides/local-development/starting-a-new-project',
        'how-to-guides/local-development/setting-up-your-environment',
        'how-to-guides/local-development/installing-cli-node-manager',
        'how-to-guides/local-development/obtaining-a-development-certificate',
        'how-to-guides/local-development/common-development-errors',
      ],
    },
    /* {
      type: 'category',
      label: 'Process Logic',
      collapsed: true,
      items: [
        'how-to-guides/process-logic/publishing-to-event-streams',
        'how-to-guides/process-logic/subscribing-to-event-streams',
        'how-to-guides/process-logic/computing-states-from-events',
        'how-to-guides/process-logic/automating-decision-making',
        'how-to-guides/process-logic/dealing-with-network-partitions',
        'how-to-guides/process-logic/modelling-processes-in-twins',
        'how-to-guides/process-logic/transferring-twins-into-code',
      ],
    }, 
    {
      type: 'category',
      label: 'Actyx SDK',
      collapsed: true,
      items: ['how-to-guides/sdk/placeholder'],
    },*/
    {
      type: 'category',
      label: 'Actyx Pond',
      collapsed: true,
      items: [
        'how-to-guides/actyx-pond/introduction',
        'how-to-guides/actyx-pond/getting-started',
        {
          type: 'category',
          label: 'Pond in 10 Steps',
          collapsed: true,
          items: [
            'how-to-guides/actyx-pond/guides/events',
            'how-to-guides/actyx-pond/guides/hello-world',
            'how-to-guides/actyx-pond/guides/integrating-a-ui',
            'how-to-guides/actyx-pond/guides/local-state',
            'how-to-guides/actyx-pond/guides/snapshots',
            'how-to-guides/actyx-pond/guides/state-effects',
            'how-to-guides/actyx-pond/guides/subscriptions',
            'how-to-guides/actyx-pond/guides/time-travel',
            'how-to-guides/actyx-pond/guides/typed-tags',
            'how-to-guides/actyx-pond/guides/types',
          ],
        },
        {
          type: 'category',
          label: 'Fish Parameters',
          collapsed: true,
          items: [
            'how-to-guides/actyx-pond/fish-parameters/deserialize-state',
            'how-to-guides/actyx-pond/fish-parameters/fish-id',
            'how-to-guides/actyx-pond/fish-parameters/initial-state',
            'how-to-guides/actyx-pond/fish-parameters/is-reset',
            'how-to-guides/actyx-pond/fish-parameters/on-event',
            'how-to-guides/actyx-pond/fish-parameters/where',
          ],
        },
        {
          type: 'category',
          label: 'Pond in-Depth',
          collapsed: true,
          items: [
            'how-to-guides/actyx-pond/in-depth/cycling-states',
            'how-to-guides/actyx-pond/in-depth/do-not-ignore-events',
            'how-to-guides/actyx-pond/in-depth/eventual-consistency',
            'how-to-guides/actyx-pond/in-depth/exception-handling',
            'how-to-guides/actyx-pond/in-depth/observe-all',
            'how-to-guides/actyx-pond/in-depth/observe-one',
            'how-to-guides/actyx-pond/in-depth/tag-type-checking',
          ],
        },
        'how-to-guides/actyx-pond/pond-extensions',
      ],
    },
    {
      type: 'category',
      label: 'Data import and export',
      collapsed: true,
      items: [
        'how-to-guides/integrating-with-actyx/user-interface',
        'how-to-guides/integrating-with-actyx/other-software',
        'how-to-guides/integrating-with-actyx/front-end-frameworks',
        'how-to-guides/integrating-with-actyx/plcs',
        'how-to-guides/integrating-with-actyx/erps',
        'how-to-guides/integrating-with-actyx/bi-analytics',
      ],
    },
    {
      type: 'category',
      label: 'Testing',
      collapsed: true,
      items: [
        'how-to-guides/testing/testing-pipeline',
        'how-to-guides/testing/unit-testing-with-jest',
        'how-to-guides/testing/unit-testing-with-cypress',
        'how-to-guides/testing/integration-testing',
        'how-to-guides/testing/ci-cd-pipeline',
      ],
    },
    {
      type: 'category',
      label: 'Packaging & Deployment',
      collapsed: true,
      items: [
        'how-to-guides/configuring-and-packaging/front-end-apps',
        'how-to-guides/configuring-and-packaging/headless-apps',
        'how-to-guides/configuring-and-packaging/deployment-to-production',
        'how-to-guides/configuring-and-packaging/updating-a-solution',
        'how-to-guides/configuring-and-packaging/actyx-swarms',
        'how-to-guides/configuring-and-packaging/bootstrap-node',
      ],
    },
    {
      type: 'category',
      label: 'Monitoring & Debugging',
      collapsed: true,
      items: [
        'how-to-guides/monitoring-debugging/node-logs',
        'how-to-guides/monitoring-debugging/app-logs',
        'how-to-guides/monitoring-debugging/connectivity-status',
        'how-to-guides/monitoring-debugging/mobile-device-management',
        'how-to-guides/monitoring-debugging/bash',
      ],
    },
    {
      type: 'category',
      label: 'Common Use-Cases',
      collapsed: true,
      items: [
        'how-to-guides/common-use-cases/showing-data-on-a-dashboard',
        'how-to-guides/common-use-cases/erp-orders-on-tablets',
        'how-to-guides/common-use-cases/controlling-agvs',
        'how-to-guides/common-use-cases/parameterise-assembly-tool',
      ],
    },
  ],
  conceptualSidebar: [
    {
      type: 'category',
      label: 'Conceptual Guides',
      collapsed: false,
      items: ['conceptual-guides/overview'],
    },
    {
      type: 'category',
      label: 'Contents',
      collapsed: false,
      items: [
        'conceptual-guides/event-based-systems',
        'conceptual-guides/distributed-system-architectures',
        'conceptual-guides/local-first-computing',
        'conceptual-guides/thinking-in-actyx',
        'conceptual-guides/actyx-jargon',
        'conceptual-guides/actyx-vs-the-cloud',
        'conceptual-guides/peer-discovery',
        'conceptual-guides/performance-and-limits-of-actyx',
        'conceptual-guides/security-in-actyx',
        'conceptual-guides/the-actyx-node',
        'conceptual-guides/actyx-node-lifecycle',
        'conceptual-guides/apps-in-the-factory-context',
      ],
    },
  ],
  referenceSidebar: [
    {
      type: 'category',
      label: 'Reference Documentation',
      collapsed: false,
      items: ['reference/overview'],
    },
    {
      type: 'category',
      label: 'Contents',
      collapsed: false,
      items: [
        'reference/actyx-api',
        'reference/js-ts-sdk',
        'reference/rust-sdk',
        'reference/cli',
        'reference/node-manager',
      ],
    },
  ],
  pondSidebar: [],
}
