[package]
name = "settings"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
anyhow = "1.0.42"
log = "0.4.14"
multiaddr = "0.13.0"
parking_lot = "0.11.1"
rusqlite = { version = "0.25.3", features = ["bundled", "backup"] }
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
structopt = "0.3.22"
thiserror = "1.0.26"
tracing = "0.1.26"
treediff = { version = "4.0.0", features = ["with-serde-json"] }
url = "2.2.2"
valico = "3.6.0"

[dev-dependencies]
maplit = "1.0.2"
rand = "0.8.4"
tempfile = "3.2.0"
