[package]
edition = { workspace = true }
name = "settings"
version = "0.1.0"
authors = ["Actyx AG"]

[dependencies]
anyhow = "1.0.52"
log = "0.4.14"
multiaddr = "0.16.0"
parking_lot = "0.12.1"
rusqlite = { version = "0.26.3", features = ["bundled", "backup"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_json = "1.0.74"
structopt = "0.3.25"
thiserror = "1.0.30"
tracing = "0.1.29"
treediff = { version = "4.0.2", features = ["with-serde-json"] }
url = "2.2.2"
valico = "3.6.0"

[dev-dependencies]
maplit = "1.0.2"
rand = "0.8.4"
tempfile = "3.3.0"
