[package]
name = "util"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
actyx_sdk = { path = "../../sdk" }
anyhow = "1.0.40"
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
crossbeam = "0.8.0"
derive_more = "0.99.13"
fnv = "1.0.7"
futures = { version = "0.3.14", package = "futures" }
libipld = { version = "0.12.0", default-features = false, features = ["dag-cbor", "derive"] }
libp2p-streaming-response = { path = "../libp2p-streaming-response" }
log-panics = "2.0.0"
multiaddr = "0.12.0"
num-traits = "0.2.14"
parking_lot = "0.11.1"
pin-utils = "0.1.0"
rand = { version = "0.8.3", features = ["small_rng"] }
serde = { version = "1.0.125", features = ["derive"] }
serde_cbor = { version = "0.11.1", features = ["tags"] }
serde_json = "1.0.64"
serde_yaml = "0.8.17"
settings = { path = "../settings" }
tracing = "0.1.25"
tracing-log = "0.1.2"
tracing-subscriber = "0.2.17"
winres = { git = "https://github.com/Actyx/winres", branch = "cross_compile" }

[dev-dependencies]
pin-utils = "0.1.0"
quickcheck = "1.0.3"
tokio = { version = "1.6.1", features = ["full"] }
waker-fn = "1.1.0"
