[package]
name = "util"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
actyx_sdk = { path = "../../sdk" }
anyhow = "1.0.52"
async-trait = "0.1.52"
base64 = "0.13.0"
cbor-data = { version = "0.8.3", features = ["rfc3339"] }
chrono = { version = "0.4.19", features = ["serde"] }
crossbeam = "0.8.1"
derive_more = "0.99.17"
fnv = "1.0.7"
futures = { version = "0.3.19", package = "futures" }
genawaiter = { version = "0.99.1", features = ["futures03"], default-features = false }
libipld = { version = "0.12.0", default-features = false, features = ["dag-cbor", "derive"] }
libp2p = { version = "0.43.0", default-features = false, features = ["request-response"] }
libp2p-streaming-response = { path = "../libp2p-streaming-response" }
log-panics = "2.0.0"
multiaddr = "0.14.0"
num-traits = "0.2.14"
parking_lot = "0.11.2"
pin-utils = "0.1.0"
rand = { version = "0.8.4", features = ["small_rng"] }
serde = { version = "1.0.133", features = ["derive"] }
serde_cbor = { version = "0.11.2", features = ["tags"] }
serde_json = "1.0.74"
serde_yaml = "0.8.23"
settings = { path = "../settings" }
tracing = "0.1.29"
tracing-log = "0.1.2"
tracing-subscriber = { version = "0.3.5", features = ["env-filter"] }
winres = { git = "https://github.com/Actyx/winres", branch = "cross_compile" }

[dev-dependencies]
pin-utils = "0.1.0"
quickcheck = "1.0.3"
tokio = { version = "1.15.0", features = ["full"], package = "tokio" }
waker-fn = "1.1.0"
