[package]
name = "util"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
actyxos_sdk = { path = "../../sdk" }
anyhow = "1.0.38"
settings = { path = "../settings" }
base64 = "0.13.0"
chrono = { version = "0.4.19", features = ["serde"] }
clap = "2.33.3"
crossbeam = "0.8.0"
derive_more = "0.99.11"
fnv = "1.0.7"
futures = { version = "0.3.13", package = "futures" }
libp2p-streaming-response = { path = "../libp2p-streaming-response" }
log-panics = "2.0.0"
lru-cache = "0.1.2"
num-traits = "0.2.14"
parity-multiaddr = "0.11.1"
parking_lot = "0.11.1"
pin-utils = "0.1.0"
rand = { version = "0.8.3", features = ["small_rng"] }
serde = { version = "1.0.124", features = ["derive"] }
serde_cbor = { version = "0.11.1", features = ["tags"] }
serde_json = "1.0.64"
tokio = { version = "1.3.0", features = ["full"], package = "tokio" }
tracing = "0.1.25"
tracing-log = "0.1.2"
tracing-subscriber = "0.2.17"
winres = { git = "https://github.com/Actyx/winres", branch = "cross_compile" }

[target.'cfg(target_os = "android")'.dependencies]
rogcat = "0.4.1"
maplit = "1.0.2"

[dev-dependencies]
maplit = "1.0.2"
futures-test = "0.3.13"
pin-utils = "0.1.0"
itertools = "0.10.0"
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
waker-fn = "1.1.0"
