[package]
name = "swarm-cli"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
actyx_sdk = { path = "../../../sdk" }
anyhow = "1.0.52"
api = { path = "../../api" }
async-process = "1.3.0"
ax-futures-util = { path = "../../ax-futures-util/" }
chrono = "0.4.19"
crossbeam = "0.8.1"
crypto = { path = "../../crypto" }
futures = { version = "0.3.19", package = "futures" }
hex = "0.4.3"
ipfs-embed = { version = "0.23", default-features = false, features = ["tokio"] }
libipld = { version = "0.12.0", features = ["dag-cbor"], default-features = false }
libp2p = { version = "0.42.1", default-features = false }
parking_lot = "0.11.2"
serde_json = "1.0.74"
structopt = "0.3.25"
swarm = { path = ".." }
tokio = { version = "1.15.0", package = "tokio" }
tracing = "0.1.29"
tracing-subscriber = "0.3.5"
trees = { path = "../../trees" }
util = { path = "../../util" }
