[package]
edition = "2021"
name = "swarm-cli"
version = "0.1.0"
authors = ["Actyx AG"]

[dependencies]
acto = "0.2.9"
actyx_sdk = { path = "../../../sdk" }
anyhow = "1.0.52"
async-process = "1.3.0"
ax = { path = "../../ax" }
cbor-data = "0.8.7"
chrono = "0.4.19"
crossbeam = "0.8.1"
futures = { version = "0.3.19", package = "futures" }
hex = "0.4.3"
ipfs-embed = { version = "0.26.0", default-features = false, features = [
  "tokio",
] }
libp2p = { version = "0.50.0", default-features = false }
log-panics = "2.1.0"
parking_lot = "0.12.1"
serde_json = "1.0.74"
structopt = "0.3.25"
tokio = { version = "1.15.0", package = "tokio" }
tracing = "0.1.29"
tracing-appender = "0.2.2"
tracing-log = "0.1.2"
tracing-subscriber = "0.3.5"
