[package]
name = "api"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
actyxos_sdk = { version = "0.5", path = "../../sdk" }
ax-futures-util = { path = "../ax-futures-util" }
crypto = { path = "../crypto" }
ipfs-node = { path = "../ipfs-node" }
trees = { path = "../trees" }
store-core = { path = "../store-core" }
util = { path = "../util" }
wsrpc = { path = "../wsrpc" }

anyhow = "1.0.38"
async-trait = "0.1.42"
chrono = { version = "0.4.19", features = ["serde"] }
derive_more = "0.99.11"
futures = "0.3.12"
hyper = { version = "0.14.4", features = ["http1", "server", "tcp"], package = "hyper" }
itertools = "0.10.0"
libipld = { version = "0.11.0", default-features = false }
maplit = "1.0.2"
mime_guess = "2.0.3"
num-traits = "0.2.14"
parking_lot = "0.11.1"
pin-project = "1.0.5"
serde = { version = "1.0.123", features = ["derive"] }
serde_cbor = "0.11.1"
serde_json = "1.0.62"
socket2 = "0.3.19"
thiserror = "1.0.23"
tokio = "1.2.0"
tracing = "0.1.22"
tree_magic = "0.2.3"
warp = "0.3.0"

[dev-dependencies]
bytes = "1.0.1"
env_logger = "0.8.3"
futures-test = "0.3.12"
ipfs-node = { path = "../ipfs-node" }
maplit = "1.0.2"
multihash = { version = "0.13.2", features = ["sha2"] }
serde_json = { version = "1.0.61", features = ["raw_value"] }
tokio = { version = "1.2.0", features = ["full"], package = "tokio" }
tracing-futures = "0.2.4"
