[package]
name = "tracing_win_event_log"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"
keywords = ["tracing", "windows event log"]

[dependencies]
tracing = "0.1.25"
tracing-subscriber = "0.2.17"
winapi = { version = "0.3.9", features = [ "winbase" ] }
