[package]
name = "ax"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[[bin]]
name = "ax"
path = "src/main.rs"

[lib]
name = "axlib"
path = "src/lib.rs"

[dependencies]
actyx_sdk = { path = "../../sdk" }
anyhow = "1.0.52"
banyan = "0.17.1"
banyan-utils = "0.10.1"
base64 = "0.13.0"
bytes = "1.1.0"
cbor-data = { version = "0.8.3", features = ["rfc3339"] }
certs = { path = "../certs" }
chrono = { version = "0.4.19", features = ["serde"] }
console = "0.15.0"
crypto = { path = "../crypto/" }
derive_more = "0.99.17"
dirs = "4.0.0"
fslock = "=0.1.6"
futures = { version = "0.3.19", features = ["compat"], package = "futures" }
genawaiter = { version = "0.99.1", features = ["futures03"] }
hex = "0.4.3"
hyper = { version = "0.14.16", features = ["stream"], package = "hyper" }
ipfs-sqlite-block-store = "0.11.0"
lazy_static = "1.4.0"
libipld = "0.12.0"
libp2p = { version = "0.42.2", default-features = false, features = ["tcp-tokio", "dns-tokio", "noise", "request-response"] }
libp2p-streaming-response = { path = "../libp2p-streaming-response" }
maplit = "1.0.2"
prettytable-rs = "0.8.0"
rand = "0.8.4"
serde = "1.0.133"
serde_json = "1.0.74"
serde_yaml = "0.8.23"
settings = { path = "../settings" }
structopt = { version = "0.3.25", features = ["color", "wrap_help", "suggestions"] }
swarm = { path = "../swarm" }
tempfile = "3.3.0"
tokio = { version = "1.15.0", features = ["full"], package = "tokio" }
tracing = { version = "0.1.29", features = ["max_level_trace", "release_max_level_trace"] }
tracing-subscriber = "0.3.5"
trees = { path = "../trees" }
tungstenite = { version = "0.16.0", features = ["native-tls"] }
util = { path = "../util" }
zstd = "0.9.2"

[dev-dependencies]
assert_cmd = "2.0.2"
derive_more = "0.99.17"
escargot = "0.5.7"
parking_lot = "0.11.2"
predicates = "2.1.0"
regex = "1.5.4"
serde_json = "1.0.74"

[build-dependencies]
util = { path = "../util" }
