[package]
edition = { workspace = true }
name = "ax"
version = "0.1.0"
authors = ["Actyx AG"]

[[bin]]
name = "ax"
path = "src/main.rs"

[lib]
name = "axlib"
path = "src/lib.rs"

[build-dependencies]
prost-build = "0.9.0"
util = { path = "../util" }

[dependencies]
acto = { version = "0.2.0", features = ["tokio"] }
actyx_sdk = { path = "../../sdk" }
anyhow = "1.0.52"
api = { path = "../api" }
atty = "0.2.14"
ax-futures-util = { path = "../ax-futures-util" }
backtrace = "0.3.63"
banyan = "0.18.0"
banyan-utils = "0.11.0"
base64 = "0.13.0"
bytes = "1.1.0"
cbor-data = { version = "0.8.7", features = ["rfc3339", "derive"] }
certs = { path = "../certs" }
cfg-if = "1.0.0"
chrono = { version = "0.4.19", features = ["serde"] }
console = "0.15.0"
crossbeam = "0.8.1"
crypto = { path = "../crypto/" }
derive_more = "0.99.17"
dirs = "4.0.0"
ffi-support = "0.4.4"
flate2 = "1.0.22"
fslock = "=0.1.6"
futures = { version = "0.3.19", features = ["compat"], package = "futures" }
genawaiter = { version = "0.99.1", features = ["futures03"] }
glob = "0.3.1"
hex = "0.4.3"
hyper = { version = "0.14.16", features = ["stream"], package = "hyper" }
im = { version = "15.1.0", features = ["serde"] }
ipfs-embed = { version = "0.26.0", default-features = false, features = ["tokio"] }
ipfs-sqlite-block-store = "0.13.0"
itertools = "0.10.5"
lazy_static = "1.4.0"
libipld = "0.14.0"
libp2p = { version = "0.50.0", default-features = false, features = ["dns", "gossipsub", "macros", "noise", "ping", "request-response", "tcp", "tokio"] }
libp2p-streaming-response = { path = "../libp2p-streaming-response" }
log = { version = "0.4.14", features = ["std"] }
maplit = "1.0.2"
multihash = "0.16.3"
parking_lot = "0.12.1"
prettytable-rs = "0.8.0"
prost = "0.9.0"
prost-derive = "0.9.0"
rand = "0.8.4"
regex = "1.5.4"
runtime = { path = "../runtime" }
rusqlite = { features = ["bundled", "backup", "hooks"], version = "0.26.3" }
serde = { features = ["derive"], version = "1.0.133" }
serde_cbor = "0.11.2"
serde_json = "1.0.74"
serde_urlencoded = "0.7.0"
serde_yaml = "0.8.23"
settings = { path = "../settings" }
signal-hook = "0.3.13"
structopt = { version = "0.3.25", features = ["color", "wrap_help", "suggestions"] }
swarm = { path = "../swarm" }
tar = "0.4.38"
tempfile = "3.3.0"
thiserror = "1.0.30"
tokio = { version = "1.15.0", features = ["full"], package = "tokio" }
tracing = { version = "0.1.29", features = ["max_level_trace", "release_max_level_trace"] }
tracing-core = "0.1.21"
tracing-log = { version = "0.1.2", features = ["std"] }
tracing-subscriber = { version = "0.3.5", features = ["json", "env-filter"] }
trees = { path = "../trees" }
tungstenite = { version = "0.16.0", features = ["native-tls"] }
unicode-width = "0.1.9"
util = { path = "../util" }
uuid = "0.8.2"
void = "1.0.2"
zeroize = "1.2.0"
zstd = "0.9.2"

[dev-dependencies]
actyx_sdk = { path = "../../sdk", features = ["client"] }
assert_cmd = "2.0.2"
criterion = { version = "0.3.5", features = ["html_reports", "async_tokio" ] }
derive_more = "0.99.17"
escargot = "0.5.7"
flate2 = "1.0.24"
maplit = "1.0.2"
once_cell = "1.16.0"
parking_lot = "0.12.1"
predicates = "2.1.0"
regex = "1.5.4"
reqwest = { version = "0.11.12", features = ["blocking"] }
serde_json = "1.0.74"
tar = "0.4.38"
tracing-subscriber = "0.3.5"
url = "2.2.2"

[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies]
jemallocator = "0.3.2"

[target.'cfg(target_os = "android")'.dependencies]
tracing-android = "0.2.0"

[[bench]]
name = "local_event_roundtrip"
harness = false