[package]
name = "ax"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[[bin]]
name = "ax"
path = "src/main.rs"

[lib]
name = "axlib"
path = "src/lib.rs"

[dependencies]
actyx_sdk = { path = "../../sdk" }
anyhow = "1.0.42"
certs = { path = "../certs" }
settings = { path = "../settings" }
banyan = "0.16.0"
banyan-utils = "0.9.0"
base64 = "0.13.0"
bytes = "1.0.1"
chrono = { version = "0.4.19", features = ["serde"] }
crypto = { path = "../crypto/" }
derive_more = "0.99.16"
dirs = "3.0.2"
futures = { version = "0.3.15", features = ["compat"], package = "futures" }
hex = "0.4.3"
hyper = { version = "0.14.10", features = ["stream"], package = "hyper" }
ipfs-sqlite-block-store = "0.7.0"
lazy_static = "1"
libipld = "0.12.0"
libp2p = { version = "0.40.0", default-features = false }
libp2p-streaming-response = { path = "../libp2p-streaming-response" }
maplit = "1.0.2"
prettytable-rs = "0.8.0"
rand = "0.8.4"
serde = "1.0.126"
serde_json = "1.0.64"
serde_yaml = "0.8.17"
structopt = "0.3.22"
swarm = { path = "../swarm" }
tempfile = "3.2.0"
tokio = { version = "1.8.2", features = ["full"], package = "tokio" }
tracing = { version = "0.1.26", features = ["max_level_trace", "release_max_level_trace"] }
tracing-subscriber = "0.2.19"
trees = { path = "../trees" }
util = { path = "../util" }

[dev-dependencies]
assert_cmd = "2.0.0"
derive_more = "0.99.16"
escargot = "0.5.2"
parking_lot = "0.11.1"
predicates = "2.0.0"
regex = "1.5.4"
serde_json = "1.0.64"

[build-dependencies]
util = { path = "../util" }
