[package]
edition = "2021"
name = "ax"
version = "0.1.0"
authors = ["Actyx AG"]

[build-dependencies]
winres = { git = "https://github.com/Actyx/winres", branch = "cross_compile" }

[dependencies]
anyhow = "1.0.66"
ax_core = { version = "0.2.0", path = "../ax-core" }
structopt = { version = "0.3.25", features = [
  "color",
  "wrap_help",
  "suggestions",
] }
tokio = { version = "1.15.0", features = ["full"] }
