[package]
name = "cosmos-release"
version = "0.1.0"
authors = ["Actyx AG"]
description = "Releases from Cosmos"
edition = "2018"

[dependencies]
anyhow = "1.0"
azure_sdk_for_rust = "0.12.0"
chrono = "0.4.19"
clap = "3.0.0-beta.2"
derive_more = "0.99"
git2 = "0.13"
itertools = "0.10.0"
rayon = "1.5.1"
regex = "1"
semver = { version = "0.11", features = ["serde"] }
tempfile = "3.2.0"
