[package]
name = "node-ffi"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
ax-os-settings = { path = "../ax-os-settings" }
node = { path = "../node" }

anyhow = "1.0.38"
crossbeam = "0.8.0"
ffi-support = "0.4.2"
futures = "0.3.12"
lazy_static = "1.4.0"
parking_lot = "0.11.1"
serde_json = "1.0.61"
tokio = { version = "1.2.0", features = ["full"] }
tracing = "0.1.22"

[lib]
crate-type = ["cdylib"]
name = "axosnodeffi"
