[package]
name = "crypto"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
actyxos_sdk = { path = "../../rust/sdk" }

aes-stream = "0.2.1"
anyhow = "1.0.38"
base64 = "0.13.0"
byteorder = { version = "1.4.2", features = ["i128"] }
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
libp2p = { version = "0.35.0", default-features = false }
multihash = { version = "0.13.2", features = ["identity"] }
rand = "0.7.3"
rust-crypto = { version = "0.2.36", package = "rust-crypto" }
serde = { version = "1.0.123", features = ["derive"] }
serde_cbor = "0.11.1"
sha2 = "0.9.2"
parking_lot = "0.11.1"
