# All the settings that are commented out are unstable as of 2019-04-30,
# and will both generate warnings, as well as not have any effect,
# when not run with the nigtly toolchain

edition = "2021"
force_explicit_abi = true
hard_tabs = false
imports_granularity = "Crate"
max_width = 120
merge_derives = true
newline_style = "Auto"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Default"
