[package]
name = "store-core"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
actyxos_sdk = { version = "0.5", features = ["sqlite", "arb"], path = "../../sdk" }
ax-config = { path = "../ax-config" }
ax-futures-util = { path = "../ax-futures-util" }
ipfs-node = { path = "../ipfs-node" }
lake = { path = "../lake" }
trees = { path = "../trees" }
util = { path = "../util" }

anyhow = "1.0.38"
banyan = "0.8.1"
fnv = "1.0.7"
futures = { version = "0.3.12", package = "futures" }
hex = "0.4.2"
ipfs-sqlite-block-store = "0.2.0"
itertools = "0.10.0"
libipld = { version = "0.11.0", default-features = false }
num-traits = "0.2.14"
parking_lot = "0.11.1"
rayon = "1.5.0"
rusqlite = { version = "0.24.2", features = ["bundled", "backup"] }
serde = { version = "1.0.123", features = ["derive"] }
serde_bytes = "0.11.5"
serde_cbor = "0.11.1"
tokio = { version = "1.0.2", features = ["full"] }
tracing = { version = "0.1.22", features = ["max_level_trace", "release_max_level_debug"] }
zstd = "0.6.0"

[dev-dependencies]
assert-json-diff = "2.0.0"
maplit = "1.0.2"
quickcheck = "1.0.3"
rstest = "0.6.4"
serde_json = "1.0.62"
tempdir = "0.3.7"
tracing-log = "0.1.2"
tracing-subscriber = "0.2.15"
