[package]
edition = { workspace = true }
name = "trees"
version = "0.1.0"
authors = ["Actyx AG"]

[dependencies]
actyx_sdk = { path = "../../sdk", features = ["arb"] }

anyhow = "1.0.52"
banyan = "0.18.0"
libipld = { version = "0.14.0", default-features = false, features = ["dag-cbor", "derive"] }
num-traits = "0.2.14"
quickcheck = { version = "1.0.3", optional = true }
range-collections = "0.1.1"
serde = { version = "1.0.133", features = ["derive"] }
smallvec = "1.7.0"
vec-collections = "0.3.5"
cbor-tag-index = "0.3.0"
derive_more = "0.99.17"

[dev-dependencies]
anyhow = { version = "1", features = ["backtrace"] }
futures = { version = "0.3.19", package = "futures" }
multihash = { version = "0.16.3", default-features = false, features = ["sha2"] }
parking_lot = "0.12.1"
pretty_assertions = "1.3.0"
quickcheck = "1.0.3"
serde_cbor = "0.11.2"
serde_json = "1.0.74"
tokio = { version = "1.15.0", features = ["full"], package = "tokio" }
zstd = "0.9.2"

[features]
arb = ["quickcheck"]
