[package]
name = "trees"
version = "0.1.0"
authors = ["Actyx AG"]
edition = "2018"

[dependencies]
actyxos_sdk = { version = "0.6", path = "../../sdk" }

anyhow = "1.0.40"
banyan = "0.12.0"
libipld = { version = "0.11.0", default-features = false, features = ["dag-cbor", "derive"] }
num-traits = "0.2.14"
quickcheck = { version = "1.0.3", optional = true }
range-collections = "0.1.1"
serde = { version = "1.0.125", features = ["derive"] }
smallvec = "1.6.1"
vec-collections = "0.3.5"

[dev-dependencies]
futures = { version = "0.3.14", package = "futures" }
multihash = { version = "0.13.2", default-features = false, features = ["sha2"] }
parking_lot = "0.11.1"
quickcheck = "1.0.3"
serde_cbor = "0.11.1"
serde_json = "1.0.64"
tokio = { version = "1.5.0", features = ["full"] }
zstd = "0.7.0"

[features]
arb = ["quickcheck"]
