[package]
authors = ["Actyx AG"]
edition = "2018"
name = "node"
version = "2.0.0-dev"

[[bin]]
name = "actyx-linux"
path = "src/bin/linux.rs"

[build-dependencies]
prost-build = "0.7.0"

[dependencies]
actyx_sdk = { version = "0.1", path = "../../sdk" }
api = { path = "../api" }
ax-futures-util = { path = "../ax-futures-util" }
settings = { path = "../settings" }
crypto = { path = "../crypto/" }
libp2p-streaming-response = { path = "../libp2p-streaming-response" }
logsvcd = { path = "../logsvcd" }
swarm = { path = "../swarm" }
trees = { path = "../trees" }
util = { path = "../util" }

anyhow = "1.0.40"
backtrace = "0.3.57"
base64 = "0.13.0"
bytes = "1.0.1"
chrono = { features = ["serde"], version = "0.4.19" }
crossbeam = "0.8.0"
derive_more = "0.99.13"
ffi-support = "0.4.2"
futures = { version = "0.3.14", features = ["compat"], package = "futures" }
libp2p = { version = "0.38.0", default-features = false, features = ["gossipsub", "ping"] }
maplit = "1.0.2"
multihash = "0.14.0"
parking_lot = "0.11.1"
prost = "0.7.0"
prost-derive = "0.7.0"
regex = "1.4.5"
rusqlite = { features = ["bundled", "backup", "hooks"], version = "0.25.1" }
serde = { features = ["derive"], version = "1.0.125" }
serde_cbor = "0.11.1"
serde_json = "1.0.64"
serde_urlencoded = "0.7.0"
signal-hook = "0.3.8"
structopt = "0.3.21"
tempfile = "3.2.0"
thiserror = "1.0.24"
tokio = { package = "tokio", version = "1.5.0" }
tracing = { version = "0.1.25", features = ["release_max_level_trace"] }
uuid = "0.8.2"
void = "1.0.2"
warp = "0.3.1"
fslock = "0.1.6"

[target.'cfg(all(target_env = "musl", target_pointer_width = "64"))'.dependencies]
jemallocator = "0.3.2"

[lib]
crate-type = ["lib"]
name = "node"

[dev-dependencies]
actyx_sdk = { version = "0.1", path = "../../sdk", features = ["client"] }
criterion = { version = "0.3.4", features = ["html_reports", "async_tokio" ] }
maplit = "1.0.2"
tracing-subscriber = "0.2.17"
url = "2.2.1"

[target."cfg(target_os = \"windows\")".dependencies]
systray = "0.4.0"
wintrap = "0.3.0"
named-lock = "0.1.1"

[[bench]]
name = "local_event_roundtrip"
harness = false
