import React from "react"

export { default as HomeIcon } from "./Home"
export { default as UserIcon } from "./User"
export { default as PreferencesIcon } from "./Preferences"
export { default as DocumentIcon } from "./Document"
export { default as InboxIcon } from "./Inbox"
export { default as BarChartIcon } from "./BarChart"
export { default as Cube3DIcon } from "./Cube3D"
export { default as VerticalTripleDots } from "./VerticalTripleDots"
export { default as HelpIcon } from "./Help"
export { default as SignatureIcon } from "./Signature"
export { default as ShieldIcon } from "./Shield"
export { default as SolidStarIcon } from "./SolidStar"
export { default as UnsolidStarIcon } from "./UnsolidStar"
export { default as NodeManagerIcon } from "./NodeManager"
export { default as KeyIcon } from "./Key"
export { default as ClipboardIcon } from "./Clipboard"
export { default as ClipboardCheckedIcon } from "./ClipboardChecked"
export { default as SearchIcon } from "./Search"
