---
- name: Install OpenSSHD
  win_chocolatey:
    name: openssh
    version: "{{ pw_openssh_version }}"
    params: "/SSHServerFeature"

- name: Create Temp Directory
  win_file:
    path: c:\temp
    state: directory

- name: Copy Install File
  win_copy:
    src: "{{ pw_package_path }}/{{ pw_package_file }}"
    dest: 'c:\temp\{{ pw_package_file }}'

- name: Install ActyxOS
  win_package:
    path: 'c:\temp\{{ pw_package_file }}'
    arguments: "{{ pw_package_args }}"
    creates_path: 'C:\Users\Administrator\AppData\Local\ActyxOS\actyx.exe'

- name: Create SSH Directory
  win_file:
    path: 'c:\Users\Administrator\.ssh'
    state: directory

- name: Copy SSH Key
  win_copy:
    src: "{{ pw_winssh_pubkey }}"
    dest: 'c:\Users\Administrator\.ssh\authorized_keys'

- name: Copy Administrator SSH KEY
  win_copy:
    src: "{{ pw_winssh_pubkey }}"
    dest: 'c:\ProgramData\ssh\administrators_authorized_keys'

- name: sshd_config replace match group
  win_lineinfile:
    path: 'c:\ProgramData\ssh\sshd_config'
    regexp: '^Match Group administrators'
    state: absent
  notify: restart_sshd

- name: sshd_config remove AuthorizedKeysFile
  win_lineinfile:
    path: 'c:\ProgramData\ssh\sshd_config'
    regexp: '^(\s*|)AuthorizedKeysFile'
    state: absent
  notify: restart_sshd
