name: Generate Artifacts

# This workflow assumes we are using a single PC for most of the tasks.
# When scaling, it might be the case that this works out of the box, or not,
# I have no clue how the GitHub runners handle the `needs` dependency between workers.

on:
  # - push
  - workflow_dispatch
  # schedule:
  #   - cron: "0 */6 * * *"
  # TODO(duarte): figure out why push-branches-master isnt working

env:
  IMAGE_VERSION: a1d06897bfcb83cb99d49fb452a87f236489cc93
  BASH_ENV: "~/.bashrc"
  NVM_VERSION: 0.39.3
  RUST_VERSION: 1.65.0

jobs:
  calculate-actyx-version:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Build release
        working-directory: rust/release
        run: cargo build --release
      - name: Calculate versions
        id: calculate-versions
        working-directory: rust/release/target/release
        run: |
          set -e
          echo "ACTYX_VERSION_ACTYX=$(./cosmos-release get-actyx-version actyx)" >> "$GITHUB_OUTPUT"
          echo "ACTYX_VERSION_CLI=$(./cosmos-release get-actyx-version cli)" >> "$GITHUB_OUTPUT"
          echo "ACTYX_VERSION_NODEMANAGER=$(./cosmos-release get-actyx-version node-manager)" >> "$GITHUB_OUTPUT"
          echo "ACTYX_VERSION_POND=$(./cosmos-release get-actyx-version pond)" >> "$GITHUB_OUTPUT"
          echo "ACTYX_VERSION_TSSDK=$(./cosmos-release get-actyx-version ts-sdk)" >> "$GITHUB_OUTPUT"
          echo "ACTYX_VERSION_RUSTSDK=$(./cosmos-release get-actyx-version rust-sdk)" >> "$GITHUB_OUTPUT"

    outputs:
      ACTYX_VERSION_ACTYX: ${{ steps.calculate-versions.outputs.ACTYX_VERSION_ACTYX }}
      ACTYX_VERSION_CLI: ${{ steps.calculate-versions.outputs.ACTYX_VERSION_CLI }}
      ACTYX_VERSION_NODEMANAGER: ${{ steps.calculate-versions.outputs.ACTYX_VERSION_NODEMANAGER }}
      ACTYX_VERSION_POND: ${{ steps.calculate-versions.outputs.ACTYX_VERSION_POND }}
      ACTYX_VERSION_TSSDK: ${{ steps.calculate-versions.outputs.ACTYX_VERSION_TSSDK }}
      ACTYX_VERSION_RUSTSDK: ${{ steps.calculate-versions.outputs.ACTYX_VERSION_RUSTSDK }}

  make-all-js:
    runs-on: self-hosted
    needs: calculate-actyx-version

    env:
      ACTYX_VERSION_ACTYX: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_ACTYX }}
      ACTYX_VERSION_CLI: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_CLI }}
      ACTYX_VERSION_NODEMANAGER: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_NODEMANAGER }}
      ACTYX_VERSION_POND: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_POND }}
      ACTYX_VERSION_TSSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_TSSDK }}
      ACTYX_VERSION_RUSTSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_RUSTSDK }}

    steps:
      - uses: actions/checkout@v3
      - name: Make All JavaScript
        run: make all-js assert-clean
      # TODO(duarte): upload artifacts to BlobStorage

  # NOTE(duarte): done, but needs uploads
  make-all-linux:
    runs-on: self-hosted
    needs: calculate-actyx-version

    env:
      ACTYX_VERSION_ACTYX: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_ACTYX }}
      ACTYX_VERSION_CLI: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_CLI }}
      ACTYX_VERSION_NODEMANAGER: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_NODEMANAGER }}
      ACTYX_VERSION_POND: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_POND }}
      ACTYX_VERSION_TSSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_TSSDK }}
      ACTYX_VERSION_RUSTSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_RUSTSDK }}

    steps:
      - uses: actions/checkout@v3
      - name: Make All Linux
        run: make all-linux assert-clean
      # TODO(duarte): upload artifacts to BlobStorage

  # NOTE(duarte): needs the CODESIGN credentials
  make-all-windows:
    runs-on: self-hosted
    needs: calculate-actyx-version

    env:
      ACTYX_VERSION_ACTYX: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_ACTYX }}
      ACTYX_VERSION_CLI: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_CLI }}
      ACTYX_VERSION_NODEMANAGER: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_NODEMANAGER }}
      ACTYX_VERSION_POND: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_POND }}
      ACTYX_VERSION_TSSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_TSSDK }}
      ACTYX_VERSION_RUSTSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_RUSTSDK }}

    steps:
      - uses: actions/checkout@v3
      - name: Make All Windows
        run: |
          mkdir -p dist/bin/ &&
          make all-windows assert-clean
      # TODO(duarte): upload artifacts to BlobStorage

  # NOTE(duarte): works but needs upload
  make-all-macos:
    runs-on: self-hosted
    needs: calculate-actyx-version

    env:
      ACTYX_VERSION_ACTYX: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_ACTYX }}
      ACTYX_VERSION_CLI: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_CLI }}
      ACTYX_VERSION_NODEMANAGER: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_NODEMANAGER }}
      ACTYX_VERSION_POND: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_POND }}
      ACTYX_VERSION_TSSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_TSSDK }}
      ACTYX_VERSION_RUSTSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_RUSTSDK }}

    steps:
      - uses: actions/checkout@v3
      - name: Make All MacOS
        run: make all-macos assert-clean
      # TODO(duarte): upload artifacts to BlobStorage

  # Works but needs upload
  make-docker:
    runs-on: self-hosted
    needs: calculate-actyx-version

    env:
      ACTYX_VERSION_ACTYX: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_ACTYX }}
      ACTYX_VERSION_CLI: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_CLI }}
      ACTYX_VERSION_NODEMANAGER: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_NODEMANAGER }}
      ACTYX_VERSION_POND: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_POND }}
      ACTYX_VERSION_TSSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_TSSDK }}
      ACTYX_VERSION_RUSTSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_RUSTSDK }}

    steps:
      - uses: actions/checkout@v3
      - name: Make Docker
        run: |
          set -e
          GIT_COMMIT=`git rev-parse HEAD`
          head_of_master=`git rev-parse origin/master`

          MASTER_TAG=""
          if [ "$GIT_COMMIT" == "$head_of_master" ]; then
              echo "Running on HEAD of master ($head_of_master), tagging image as latest"
              make -e ADDITIONAL_DOCKER_ARGS="--tag actyx/actyx-ci:actyx-latest" docker-push-actyx
          else
              make docker-push-actyx
          fi

          make assert-clean
      # TODO(duarte): upload artifacts to BlobStorage

  # NOTE: needs client tokens
  make-all-android:
    runs-on: self-hosted
    needs: calculate-actyx-version

    env:
      ACTYX_VERSION_ACTYX: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_ACTYX }}
      ACTYX_VERSION_CLI: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_CLI }}
      ACTYX_VERSION_NODEMANAGER: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_NODEMANAGER }}
      ACTYX_VERSION_POND: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_POND }}
      ACTYX_VERSION_TSSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_TSSDK }}
      ACTYX_VERSION_RUSTSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_RUSTSDK }}

    steps:
      - name: Make All Android
        run: |
          set -e
          ./jvm/os-android/bin/get-keystore.sh
          make all-android assert-clean
      # TODO(duarte): upload artifacts to BlobStorage

  make-node-manager-macos:
    runs-on: macos-12
    needs: calculate-actyx-version

    env:
      ACTYX_VERSION_ACTYX: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_ACTYX }}
      ACTYX_VERSION_CLI: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_CLI }}
      ACTYX_VERSION_NODEMANAGER: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_NODEMANAGER }}
      ACTYX_VERSION_POND: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_POND }}
      ACTYX_VERSION_TSSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_TSSDK }}
      ACTYX_VERSION_RUSTSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_RUSTSDK }}

    steps:
      - uses: actions/checkout@v3
      - name: Setup NVM
        run: |
          curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/v${NVM_VERSION}/install.sh" | bash
      - name: Setup Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain "$RUST_VERSION" -y
      - name: Upgrade brew & Install protobuf
        run: brew install make protobuf
      - name: Make Node Manager Mac
        run: gmake node-manager-mac-linux
      # TODO(duarte): upload artifacts to BlobStorage

  make-node-manager-windows:
    runs-on: [self-hosted, sudo]
    needs: calculate-actyx-version

    env:
      ACTYX_VERSION_ACTYX: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_ACTYX }}
      ACTYX_VERSION_CLI: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_CLI }}
      ACTYX_VERSION_NODEMANAGER: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_NODEMANAGER }}
      ACTYX_VERSION_POND: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_POND }}
      ACTYX_VERSION_TSSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_TSSDK }}
      ACTYX_VERSION_RUSTSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_RUSTSDK }}

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: pwd
      - name: Make Node Manager Windows
        run: make node-manager-win
      # TODO(duarte): upload artifacts to BlobStorage

  make-node-manager-linux:
    runs-on: self-hosted
    needs: calculate-actyx-version

    env:
      ACTYX_VERSION_ACTYX: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_ACTYX }}
      ACTYX_VERSION_CLI: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_CLI }}
      ACTYX_VERSION_NODEMANAGER: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_NODEMANAGER }}
      ACTYX_VERSION_POND: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_POND }}
      ACTYX_VERSION_TSSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_TSSDK }}
      ACTYX_VERSION_RUSTSDK: ${{ needs.calculate-actyx-version.outputs.ACTYX_VERSION_RUSTSDK }}

    steps:
      - name: Make Node Manager Linux
        run: make node-manager-mac-linux
      # TODO(duarte): upload artifacts to BlobStorage
