name: Periodic AWS instance cleanup
on:
  workflow_dispatch:

jobs:
  integration-cleanup:
    runs-on: [self-hosted, Linux]

    steps:
      - uses: actions/checkout@v3
      - run: |
          set -e
          make prepare-js all-js
          cd integration
          source ~/.nvm/nvm.sh
          nvm use
          npm install
          npm run cleanup 43200
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  notify-discord:
    runs-on: [self-hosted, Linux]
    if: ${{ always() }}

    needs:
      - integration-cleanup

    steps:
      - uses: jmg-duarte/discord-workflow-status@5a826a3e649f9d1157507494d35811ec2f84380c
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
