steps:
  - download: current
    artifact: actyxos-bin-$(ARCH)
    condition: contains(variables['BUILD_STRING'],'[build-rt-master]')
  - script: |
      mkdir -p ./dist/
      mv $(Pipeline.Workspace)/actyxos-bin-$(ARCH) ./dist/bin
      ls -alh ./dist/bin
      make docker-push-`echo $DOCKER_TAG|cut -f1 -d-`
    displayName: Build & Push Container
    condition: contains(variables['BUILD_STRING'],'[build-rt-master]')
    env:
      DOCKERHUB_PASS: $(SECRET_DOCKERHUB_PASS)
      GITHUB_PKG_PASS: $(SECRET_GITHUB_PKG_PASS)
  - script: |
      build/bin/post-to-slack.sh -s "ActyxOS Docker images - $DOCKER_TAG" -a "danger"
    condition: failed()
    displayName: Ping Slack on failing job
