steps:
  - template: ../../steps-bootstrap.yml
  - script: |
      docker image rm actyx/cosmos:dist-stress-test-x64-latest
      docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
      docker run -e SCCACHE_REDIS=$SCCACHE_REDIS --privileged -v $(pwd):/root/src -t --rm actyx/cosmos:dist-stress-test-x64-latest /run.sh
    displayName: Run Distributed Stress Test
    env:
      DOCKERHUB_PASS: $(SECRET_DOCKERHUB_PASS)
      SCCACHE_REDIS: $(SECRET_SCCACHE_REDIS)
  - script: |
      BUILD_LINK=https://dev.azure.com/ax-ci/Cosmos/_build/results?buildId=$BUILD_BUILDID
      build/bin/post-to-slack.sh -s "Distributed stress test" -a "danger"
    condition: failed()
    displayName: Ping Slack on failing job
