steps:
  - bash: |
      export CARGO_INCREMENTAL=0
      cargo fmt --all -- --check && \
      cargo --locked clippy -- -D warnings && \
      cargo --locked clippy --tests -- -D warnings
    displayName: fmt/clippy
    workingDirectory: rt-master
    condition: contains(variables['BUILD_STRING'],'[build-rt-master]')
  - bash: |
      cargo --locked test --jobs 8 --release -- --test-threads=1
      # TODO, maybe add docker integration tests to the distributed stress runs?
      # dockerIntegrationTests && exec('./run-docker-integration-tests.sh
    displayName: tests
    workingDirectory: rt-master
    condition: and(succeeded(),contains(variables['BUILD_STRING'],'[build-rt-master]'))
  - bash: |
      build/bin/post-to-slack.sh -s "Rusty Stuff - rt-master" -a "danger"
    condition: failed()
    displayName: Ping Slack on failing job
