jobs:
  - job: smartBuilds
    pool:
      name: Native
    displayName: Smart Builds
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "10.16.0"
        displayName: Install Node
      - script: |
          # This diffs files on the current PR and the relevant Cosmos branch this PR was branched from
          BASE_HASH=$(echo $BUILD_SOURCEVERSIONMESSAGE | cut -f 4 -d " ")
          FILE_CHANGES=$(git diff --name-only $SYSTEM_PULLREQUEST_SOURCECOMMITID $BASE_HASH) node build/bin/smart-builds/smart-builds.js
        name: runSmartBuilds
        displayName: Run Smart Builds
      - publish: $(Pipeline.Workspace)/variables
        artifact: variables
        displayName: Publish Pipeline Artifact
      - script: |
          build/bin/post-to-slack.sh -s "Smart Builds" -a "danger"
        condition: failed()
        displayName: Ping Slack on failing job
