jobs:
  - job: smartBuilds
    pool:
      name: Native
    displayName: Build all the things
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "10.16.0"
        displayName: Install Node
      - script: |
          set -e
          make docker-push-`echo $DOCKER_TAG|cut -f1 -d-`
          export VAULT_ADDR=https://vault.actyx.net
          $HOME/bin/vault login -method aws role=ops-travis-ci 2>&1 > /dev/null
        env:
          DOCKERHUB_PASS: $(SECRET_DOCKERHUB_PASS)
          GITHUB_PKG_PASS: $(SECRET_GITHUB_PKG_PASS)
          AWS_ACCESS_KEY_ID: $(SECRET_AWS_ACCESS_KEY_ID)
          AWS_SECRET_ACCESS_KEY: $(SECRET_AWS_SECRET_ACCESS_KEY)
        condition: contains(variables['BUILD_STRING'],variables['CURRENT_CONTAINER_BUILD_TAG'])
        displayName: Build $(DOCKER_TAG)
      - script: |
          make build-all
        name: runSmartBuilds
        displayName: Run Smart Builds
      - publish: $(Pipeline.Workspace)/variables
        artifact: variables
        displayName: Publish Pipeline Artifact
      - script: |
          build/bin/post-to-slack.sh -s "Smart Builds" -a "danger"
        condition: failed()
        displayName: Ping Slack on failing job
